# Generated by Django 5.0.2 on 2024-02-20 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notesversionhistory',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notesversionhistory',
            name='deleted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='del_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notesversionhistory',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='upd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='shared',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
