# Generated by Django 5.0.2 on 2024-02-20 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notesversionhistory_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesversionhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notesversionhistory',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notesversionhistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
