# Generated by Django 5.0.2 on 2024-02-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notesversionhistory_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesversionhistory',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='notesversionhistory',
            name='deleted_by',
        ),
    ]
